-- Add aiDescription field to ServiceMedia table
-- This field stores natural language descriptions (3-5 sentences) generated by Gemini Vision AI
-- Used to enhance multimodal embeddings for 90-100% accurate visual matching

ALTER TABLE "ServiceMedia" ADD COLUMN IF NOT EXISTS "aiDescription" TEXT;

-- Add comment to document field purpose
COMMENT ON COLUMN "ServiceMedia"."aiDescription" IS 'Comprehensive 3-5 sentence natural language description generated by Gemini Vision AI. Captures person details, hair/makeup/service specifics, tools/products, setting/lighting/atmosphere, mood/aesthetic, and professional quality. Combined with tags in multimodal embeddings for enhanced visual search accuracy.';

